name: CI - Frontend

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  frontend-tests:
    name: Run Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          cache-dependencies: true

      - name: Install dependencies
        working-directory: frontend
        run: pnpm install --no-frozen-lockfile

      - name: Run frontend build
        working-directory: frontend
        run: pnpm build

      - name: Run frontend tests
        working-directory: frontend
        run: pnpm test
